<?php
/**
 * Copyright © 2021 Neosoft Technologies. All rights reserved.
 */
?>
<!-- New custom template -->
<script type="text/template" id="autocomplete_storelocator_template">
    <a class="algoliasearch-autocomplete-hit">
        <div class="info-without-thumb">
            <div class="store_address">
                {{store_title}}, {{store_address}}, {{store_zipcode}}
            </div>
        </div>
        <div class="algolia-clearfix"></div>
    </a>
</script>
